# Generated by Django 2.2.5 on 2019-09-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateField(null=True)),
                ("stopped", models.DateField(null=True)),
                ("years", models.PositiveIntegerField(null=True)),
                ("review", models.DateField(null=True)),
                (
                    "rent",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
            ],
            options={
                "unique_together": {("started", "stopped", "years", "review", "rent")}
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
                "unique_together": {("name", "address")},
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=16, unique=True)),
                ("name", models.TextField()),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bink.Lease"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bink.Property"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bink.Tenant"
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bink.UnitType",
                        verbose_name="type",
                    ),
                ),
            ],
        ),
    ]
